// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"github.com/google/wire"
	"z-novel-ai-api/internal/config"
	"z-novel-ai-api/internal/infrastructure/messaging"
	"z-novel-ai-api/internal/infrastructure/persistence/milvus"
	"z-novel-ai-api/internal/infrastructure/persistence/postgres"
	"z-novel-ai-api/internal/infrastructure/persistence/redis"
)

// Injectors from wire.go:

// InitializeDataLayer 初始化数据层
func InitializeDataLayer(ctx context.Context, cfg *config.Config) (*DataLayer, func(), error) {
	client, cleanup, err := ProvidePostgresClient(cfg)
	if err != nil {
		return nil, nil, err
	}
	txManager := postgres.NewTxManager(client)
	tenantContext := postgres.NewTenantContext(client)
	tenantRepository := postgres.NewTenantRepository(client)
	userRepository := postgres.NewUserRepository(client)
	projectRepository := postgres.NewProjectRepository(client)
	volumeRepository := postgres.NewVolumeRepository(client)
	chapterRepository := postgres.NewChapterRepository(client)
	entityRepository := postgres.NewEntityRepository(client)
	relationRepository := postgres.NewRelationRepository(client)
	eventRepository := postgres.NewEventRepository(client)
	jobRepository := postgres.NewJobRepository(client)
	redisClient, cleanup2, err := ProvideRedisClient(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	cache := redis.NewCache(redisClient)
	rateLimiter := redis.NewRateLimiter(redisClient)
	producer := ProvideMessagingProducer(redisClient, cfg)
	milvusClient, cleanup3, err := ProvideMilvusClient(ctx, cfg)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	repository := milvus.NewRepository(milvusClient)
	dataLayer := &DataLayer{
		PgClient:      client,
		TxManager:     txManager,
		TenantContext: tenantContext,
		TenantRepo:    tenantRepository,
		UserRepo:      userRepository,
		ProjectRepo:   projectRepository,
		VolumeRepo:    volumeRepository,
		ChapterRepo:   chapterRepository,
		EntityRepo:    entityRepository,
		RelationRepo:  relationRepository,
		EventRepo:     eventRepository,
		JobRepo:       jobRepository,
		RedisClient:   redisClient,
		Cache:         cache,
		RateLimiter:   rateLimiter,
		Producer:      producer,
		MilvusClient:  milvusClient,
		VectorRepo:    repository,
	}
	return dataLayer, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// DataLayer 数据层依赖容器
type DataLayer struct {
	// PostgreSQL
	PgClient      *postgres.Client
	TxManager     *postgres.TxManager
	TenantContext *postgres.TenantContext
	TenantRepo    *postgres.TenantRepository
	UserRepo      *postgres.UserRepository
	ProjectRepo   *postgres.ProjectRepository
	VolumeRepo    *postgres.VolumeRepository
	ChapterRepo   *postgres.ChapterRepository
	EntityRepo    *postgres.EntityRepository
	RelationRepo  *postgres.RelationRepository
	EventRepo     *postgres.EventRepository
	JobRepo       *postgres.JobRepository

	// Redis
	RedisClient *redis.Client
	Cache       *redis.Cache
	RateLimiter *redis.RateLimiter

	// Messaging
	Producer *messaging.Producer

	// Milvus
	MilvusClient *milvus.Client
	VectorRepo   *milvus.Repository
}

// PostgresSet PostgreSQL 提供者集合
var PostgresSet = wire.NewSet(
	ProvidePostgresClient, postgres.NewTxManager, postgres.NewTenantContext, postgres.NewTenantRepository, postgres.NewUserRepository, postgres.NewProjectRepository, postgres.NewVolumeRepository, postgres.NewChapterRepository, postgres.NewEntityRepository, postgres.NewRelationRepository, postgres.NewEventRepository, postgres.NewJobRepository,
)

// RedisSet Redis 提供者集合
var RedisSet = wire.NewSet(
	ProvideRedisClient, redis.NewCache, redis.NewRateLimiter,
)

// MessagingSet 消息队列提供者集合
var MessagingSet = wire.NewSet(
	ProvideMessagingProducer,
)

// MilvusSet Milvus 提供者集合
var MilvusSet = wire.NewSet(
	ProvideMilvusClient, milvus.NewRepository,
)

// ProvidePostgresClient 提供 PostgreSQL 客户端
func ProvidePostgresClient(cfg *config.Config) (*postgres.Client, func(), error) {
	client, err := postgres.NewClient(&cfg.Database.Postgres)
	if err != nil {
		return nil, nil, err
	}
	cleanup := func() {
		client.Close()
	}
	return client, cleanup, nil
}

// ProvideRedisClient 提供 Redis 客户端
func ProvideRedisClient(cfg *config.Config) (*redis.Client, func(), error) {
	client, err := redis.NewClient(&cfg.Cache.Redis)
	if err != nil {
		return nil, nil, err
	}
	cleanup := func() {
		client.Close()
	}
	return client, cleanup, nil
}

// ProvideMessagingProducer 提供消息生产者
func ProvideMessagingProducer(redisClient *redis.Client, cfg *config.Config) *messaging.Producer {
	maxLen := cfg.Messaging.RedisStream.MaxLen
	if maxLen <= 0 {
		maxLen = 100000
	}
	return messaging.NewProducer(redisClient.Redis(), int64(maxLen))
}

// ProvideMilvusClient 提供 Milvus 客户端
func ProvideMilvusClient(ctx context.Context, cfg *config.Config) (*milvus.Client, func(), error) {
	client, err := milvus.NewClient(ctx, &cfg.Database.Milvus)
	if err != nil {
		return nil, nil, err
	}
	cleanup := func() {
		client.Close()
	}
	return client, cleanup, nil
}
